package eserciziCompleti.studioDentistico.grafica.mainPanels;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import eserciziCompleti.studioDentistico.gestori.GestoreImpostazioni;
import eserciziCompleti.studioDentistico.grafica.NavBarUtil;
import eserciziCompleti.studioDentistico.oggetti.Impostazioni;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;

public class HomePage {
    private static final ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
    private JPanel pannelloHomePage;
    private JPanel pannelloNavBar;
    private JPanel pannelloContenuto;
    private JLabel logo;
    private JButton btnPazienti;
    private JButton btnInterventi;
    private JButton btnFatture;
    private JLabel logoContenuto;
    private JLabel testoBenvenuto;
    private JLabel descrizioneBenvenuto;
    private JLabel labelImpostazioni;

    private JButton[] bottoniNav;

    public HomePage() {
        caricaImpostazioni();
        initGrafica();
    }

    private void caricaImpostazioni() {
        Impostazioni impostazioni;
        impostazioni = GestoreImpostazioni.getInstance().getImpostazioni();

        logo.setText("Studio Dentistico " + impostazioni.getNomeStudio());
        descrizioneBenvenuto.setText("Gestionale dello Studio Dentistico " + impostazioni.getNomeStudio());
    }

    private void initGrafica() {
        bottoniNav = new JButton[]{
                btnPazienti, btnInterventi, btnFatture
        };
        NavBarUtil.initNavBar(bottoniNav, logo, labelImpostazioni);
    }


    public JPanel getMainPanel() {
        return pannelloHomePage;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pannelloHomePage = new JPanel();
        pannelloHomePage.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloHomePage.setBackground(new Color(-13350554));
        pannelloNavBar = new JPanel();
        pannelloNavBar.setLayout(new GridLayoutManager(1, 6, new Insets(10, 20, 10, 20), -1, -1));
        pannelloNavBar.setBackground(new Color(-15919071));
        pannelloHomePage.add(pannelloNavBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logo = new JLabel();
        logo.setEnabled(true);
        Font logoFont = this.$$$getFont$$$("Kokonor", Font.BOLD, 24, logo.getFont());
        if (logoFont != null) logo.setFont(logoFont);
        logo.setForeground(new Color(-985873));
        logo.setHorizontalAlignment(0);
        logo.setHorizontalTextPosition(11);
        logo.setIcon(new ImageIcon(getClass().getResource("/studioDentistico/logoDentista.png")));
        logo.setText("Studio Dentistico ");
        pannelloNavBar.add(logo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnPazienti = new JButton();
        btnPazienti.setBackground(new Color(-14503271));
        btnPazienti.setBorderPainted(false);
        btnPazienti.setContentAreaFilled(true);
        btnPazienti.setEnabled(true);
        btnPazienti.setFocusPainted(false);
        btnPazienti.setFocusable(true);
        Font btnPazientiFont = this.$$$getFont$$$(null, Font.BOLD, 16, btnPazienti.getFont());
        if (btnPazientiFont != null) btnPazienti.setFont(btnPazientiFont);
        btnPazienti.setForeground(new Color(-15919071));
        btnPazienti.setHideActionText(false);
        btnPazienti.setHorizontalAlignment(0);
        btnPazienti.setInheritsPopupMenu(false);
        btnPazienti.setLabel("Pazienti");
        btnPazienti.setOpaque(true);
        btnPazienti.setRequestFocusEnabled(true);
        btnPazienti.setRolloverEnabled(false);
        btnPazienti.setSelected(false);
        btnPazienti.setText("Pazienti");
        btnPazienti.setVisible(true);
        pannelloNavBar.add(btnPazienti, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(130, -1), new Dimension(130, -1), new Dimension(130, -1), 0, false));
        final Spacer spacer1 = new Spacer();
        pannelloNavBar.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnInterventi = new JButton();
        btnInterventi.setBackground(new Color(-14503271));
        btnInterventi.setBorderPainted(false);
        btnInterventi.setContentAreaFilled(true);
        btnInterventi.setEnabled(true);
        btnInterventi.setFocusPainted(false);
        btnInterventi.setFocusable(false);
        Font btnInterventiFont = this.$$$getFont$$$(null, Font.BOLD, 16, btnInterventi.getFont());
        if (btnInterventiFont != null) btnInterventi.setFont(btnInterventiFont);
        btnInterventi.setForeground(new Color(-15919071));
        btnInterventi.setHideActionText(false);
        btnInterventi.setHorizontalAlignment(0);
        btnInterventi.setInheritsPopupMenu(false);
        btnInterventi.setLabel("Interventi");
        btnInterventi.setOpaque(true);
        btnInterventi.setRequestFocusEnabled(true);
        btnInterventi.setRolloverEnabled(false);
        btnInterventi.setSelected(false);
        btnInterventi.setText("Interventi");
        btnInterventi.setVisible(true);
        pannelloNavBar.add(btnInterventi, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(140, -1), new Dimension(140, -1), new Dimension(140, -1), 1, false));
        btnFatture = new JButton();
        btnFatture.setBackground(new Color(-14503271));
        btnFatture.setBorderPainted(false);
        btnFatture.setContentAreaFilled(true);
        btnFatture.setEnabled(true);
        btnFatture.setFocusPainted(false);
        btnFatture.setFocusable(false);
        Font btnFattureFont = this.$$$getFont$$$(null, Font.BOLD, 16, btnFatture.getFont());
        if (btnFattureFont != null) btnFatture.setFont(btnFattureFont);
        btnFatture.setForeground(new Color(-15919071));
        btnFatture.setHideActionText(false);
        btnFatture.setHorizontalAlignment(0);
        btnFatture.setInheritsPopupMenu(false);
        btnFatture.setLabel("Fatture");
        btnFatture.setOpaque(true);
        btnFatture.setRequestFocusEnabled(true);
        btnFatture.setRolloverEnabled(false);
        btnFatture.setSelected(false);
        btnFatture.setText("Fatture");
        btnFatture.setVisible(true);
        pannelloNavBar.add(btnFatture, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(130, -1), new Dimension(130, -1), new Dimension(130, -1), 1, false));
        labelImpostazioni = new JLabel();
        labelImpostazioni.setIcon(new ImageIcon(getClass().getResource("/studioDentistico/iconImpostazioni30.png")));
        labelImpostazioni.setText("");
        pannelloNavBar.add(labelImpostazioni, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloContenuto = new JPanel();
        pannelloContenuto.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloContenuto.setBackground(new Color(-13350554));
        pannelloHomePage.add(pannelloContenuto, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        testoBenvenuto = new JLabel();
        Font testoBenvenutoFont = this.$$$getFont$$$("Heiti SC", Font.BOLD, 48, testoBenvenuto.getFont());
        if (testoBenvenutoFont != null) testoBenvenuto.setFont(testoBenvenutoFont);
        testoBenvenuto.setForeground(new Color(-985873));
        testoBenvenuto.setText("Benvenuto");
        pannelloContenuto.add(testoBenvenuto, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pannelloContenuto.add(spacer2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        descrizioneBenvenuto = new JLabel();
        Font descrizioneBenvenutoFont = this.$$$getFont$$$("Heiti SC", Font.BOLD, 22, descrizioneBenvenuto.getFont());
        if (descrizioneBenvenutoFont != null) descrizioneBenvenuto.setFont(descrizioneBenvenutoFont);
        descrizioneBenvenuto.setForeground(new Color(-985873));
        descrizioneBenvenuto.setText("Gestionale dello Studio Dentistico");
        pannelloContenuto.add(descrizioneBenvenuto, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        pannelloContenuto.add(spacer3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        pannelloContenuto.add(spacer4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 5), new Dimension(-1, 5), new Dimension(-1, 5), 0, false));
        logoContenuto = new JLabel();
        logoContenuto.setHorizontalAlignment(10);
        logoContenuto.setHorizontalTextPosition(0);
        logoContenuto.setIcon(new ImageIcon(getClass().getResource("/studioDentistico/logoDentista200.png")));
        logoContenuto.setText("");
        pannelloContenuto.add(logoContenuto, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pannelloHomePage;
    }
}
